networks:
  default:
    name: agenda
    driver: bridge

services:
  develop-agenda:
    image: deirofelippe/develop-agenda:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: develop-agenda
    volumes:
      - "./:/home/node/app"

  agenda-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agenda-backend
    volumes:
      - "./backend:/app"
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  agenda-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agenda-frontend
    volumes:
      - "./frontend:/app"
    ports:
      - "3001:3000"
    depends_on:
      - agenda-backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda

  localstack:
    image: localstack/localstack:3.1.0
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=0
      - AWS_DEFAULT_REGION=sa-east-1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
