@host = http://agenda-backend:3000

POST {{host}}/contacts HTTP/1.1
Content-Type: application/json

{
    "name": "eu",
    "email": "eua@mail.com",
    "phone": "91235-5678",
    "image": "/path/image.png"
}

###
POST {{host}}/presigned-url HTTP/1.1
Content-Type: application/json

{
    "imageName": "dre.png"
}

###
GET {{host}}/contacts HTTP/1.1

###
GET {{host}}/contacts/b4a24da6-33b3-47fe-9c44-c8b2b2c43ef4 HTTP/1.1

###
PUT {{host}}/contacts/b4a24da6-33b3-47fe-9c44-c8b2b2c43ef4 HTTP/1.1
Content-Type: application/json

{
    "name": "euu",
    "email": "euasdua@mail.com"
}

###
DELETE {{host}}/contacts/0e430ce1-ab22-4b2f-b150-2b42b5797019 HTTP/1.1

