@host = http://18.231.238.224
# @host = http://localhost:3000
@id = 28ae3473-454d-433a-9800-d3480170b888

GET {{host}}/healthz HTTP/1.1

###
POST {{host}}/contacts HTTP/1.1
Content-Type: application/json

{
    "name": "eu",
    "email": "sdffssfd@mail.com",
    "phone": "91235-5679",
    "image": "image.png"
}

###
GET {{host}}/images/presigned-url?imageName=41df7b96-7c4a-44bc-8e55-5b19bf72edae.png HTTP/1.1

###
GET {{host}}/contacts HTTP/1.1

###
GET {{host}}/contacts/{{id}} HTTP/1.1

###
PUT {{host}}/contacts/{{id}} HTTP/1.1
Content-Type: application/json

{
    "name": "euu",
    "image": "teste.png",
}

###
PUT {{host}}/contacts/{{id}} HTTP/1.1
Content-Type: application/json

{
    "id":"{{id}}",
    "name": "euuu",
    "email": "euasdua@mail.com"
}

###
DELETE {{host}}/contacts/{{id}} HTTP/1.1

