FROM node:22.11.0-alpine3.20

RUN apk update \
    # nc ss tcpdump curl ping
    && apk add netcat-openbsd iproute2-ss tcpdump curl iputils-ping

USER node

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./

RUN npm ci

COPY --chown=node:node ./ ./

CMD ["/usr/local/bin/npm", "run", "dev"]